### ISSUE TITLE
I ma not sure this is a bugs

### ISSUE THREAD

**Issue by calvin2021y** [canonical/raft#283]
I get this in test once,  not sure how it happen.  And I can not get this error when I try more.

```sh
    ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7fa834bb5b20 in thread T0
    #0 0x5569ad40e8a2 in __interceptor_free (tests_raft+0x4728a2) (BuildId: 126294b4a9a9562b)
    #1 0x5569ad623418 in destroyEntry raft/src/log.c
    #2 0x5569ad623418 in removePrefix raft/src/log.c:882:13
    #3 0x5569ad623418 in logSnapshot raft/src/log.c:906:5
    #4 0x5569ad637129 in takeSnapshotCb raft/src/replication.c:1457:5
    #5 0x5569ad666476 in uvSnapshotPutFinish raft/src/uv_snapshot.c:569:5
    #6 0x5569ad666476 in uvSnapshotPutAfterWorkCb raft/src/uv_snapshot.c:578:5
    #7 0x5569ad5ce89c in uv__work_done uv/src/threadpool.c:334:5
    #8 0x5569ad5db15c in uv__async_io uv/src/unix/async.c:163:5
    #9 0x5569ad61975a in uv__io_poll uv/src/unix/epoll.c:374:11
    #10 0x5569ad5dc0ce in uv_run uv/src/unix/core.c:391:5
```

**Comment by MathieuBordere** [comment]
Which test was it?

**Comment by calvin2021y** [comment]
I just test on_snapshot_finalize with my own code,  I setup 1 node without others.  raft_set_snapshot_threshold 4, raft_set_snapshot_trailing 8.

I free the memory from on_snapshot_finalize callback,  It will tigger after 2 snapshot.

**Comment by calvin2021y** [comment]
set raft_set_snapshot_threshold to 2,  tigger after 4 snapshot.

**Comment by MathieuBordere** [comment]
Can you post detailed steps to reproduce please, it will be a lot easier to debug for me.

**Comment by calvin2021y** [comment]
I will try minimal my test, right now the code base is a bit mass.

**Comment by MathieuBordere** [comment]
I will close for now, once you post the minimal test, I will reopen okay?

**Comment by calvin2021y** [comment]
Turn out not a bugs.

I free the buf.base pass into  raft_apply,  at  serverApplyCb.
